//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhadKaplan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUsForm
    {
        public int ContactUsId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public Nullable<int> PlayerId { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
