//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhadKaplan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentItem
    {
        public int ConteneId { get; set; }
        public string ContetntType { get; set; }
        public string ContentText { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool DisplayInSite { get; set; }
    }
}
