//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhadKaplan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MemoryGameEntities : DbContext
    {
        public MemoryGameEntities()
            : base("name=MemoryGameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<ContactUsForm> ContactUsForms { get; set; }
        public virtual DbSet<ContentItem> ContentItems { get; set; }
        public virtual DbSet<ImagesType> ImagesTypes { get; set; }
    
        public virtual ObjectResult<GetTopScores_Result> GetTopScores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTopScores_Result>("GetTopScores");
        }
    
        public virtual ObjectResult<GetLastFeedbacks_Result> GetLastFeedbacks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLastFeedbacks_Result>("GetLastFeedbacks");
        }
    
        public virtual ObjectResult<GetFeedbacks_Result> GetFeedbacks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFeedbacks_Result>("GetFeedbacks");
        }
    
        public virtual ObjectResult<GetResults_Result> GetResults()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetResults_Result>("GetResults");
        }
    }
}
